language: cpp
sudo: false
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    packages:
      - gperf 
script:
  - cd ..
  - git clone https://github.com/espressif/esp-idf.git
  - wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-59.tar.gz
  - tar xzvf xtensa-esp32-elf-linux64-1.22.0-59.tar.gz
  - cd -
  - source ./set_env.sh
  - make
